# Generated by Django 4.2.3 on 2023-09-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='StateSnapProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SnapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('sub_programs', models.CharField(max_length=255)),
                ('snap_website', models.URLField()),
                ('state_ebt_info', models.URLField()),
                ('applications', models.ManyToManyField(to='snap_app.applicationinfo')),
                ('state_snap_program_name', models.ManyToManyField(to='snap_app.statesnapprogram')),
            ],
        ),
    ]
