# Generated by Django 4.2.3 on 2023-09-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapdata',
            old_name='state_snap_program_name',
            new_name='StateSNAPProgramName',
        ),
        migrations.RemoveField(
            model_name='applicationinfo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='applicationinfo',
            name='url',
        ),
        migrations.RemoveField(
            model_name='snapdata',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='snapdata',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='snapdata',
            name='snap_website',
        ),
        migrations.RemoveField(
            model_name='snapdata',
            name='state_ebt_info',
        ),
        migrations.RemoveField(
            model_name='snapdata',
            name='sub_programs',
        ),
        migrations.AddField(
            model_name='applicationinfo',
            name='Link',
            field=models.URLField(default='application link here'),
        ),
        migrations.AddField(
            model_name='snapdata',
            name='SNAPWebsite',
            field=models.URLField(default='snapwebsite'),
        ),
        migrations.AddField(
            model_name='snapdata',
            name='StateEBTInfo',
            field=models.URLField(default='ebtwebsite'),
        ),
        migrations.AddField(
            model_name='snapdata',
            name='SubPrograms',
            field=models.CharField(default='Supplemental Nutrition Assistance Program (SNAP)', max_length=255),
        ),
        migrations.AddField(
            model_name='applicationinfo',
            name='Description',
            field=models.CharField(default='description here', max_length=255),
        ),
        migrations.AddField(
            model_name='snapdata',
            name='Organization',
            field=models.CharField(default='Organization', max_length=255),
        ),
    ]
